version: '2'
services:
  zoneminder-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: zoneminder
        source_port: 8085
        target_port: 80
#      - protocol: https
#        service: zoneminder
#        source_port: 8443
#        target_port: 443
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  zoneminder:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 80
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
      request_line: GET / HTTP/1.0
