version: '2'
services:
  jupyter-notebook-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: jupyter-notebook
        source_port: 8888
        target_port: 8888
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  jupyter-notebook:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 8888
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
      request_line: GET / HTTP/1.0
